name: Deploy Allure Report to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and Allure CLI
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y default-jre
        curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -xvzf allure.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Download previous Allure history from gh-pages branch
      run: |
        git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages-temp
        mkdir -p allure-results/history
        cp -R gh-pages-temp/history/* allure-results/history/ || echo "🟡 No previous history found"

    - name: Run tests and generate Allure report
      run: |
        pytest --alluredir=allure-results || true
        allure generate allure-results -o allure-report --clean

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Upload updated Allure history for trend tracking
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: allure-report/history

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
